### ISSUE TITLE
First build ApkMonitor/ under Eclispe.

### ISSUE THREAD

**Issue by hellominuswang** [xurubin/aurasium#2]
Hi,
   When I building ApkMonitor under Eclispe,I am getting these following compilation errors.I have no idea what's wrong.Can you do me a favour? Thank you in advance.

Description Resource    Path    Location    Type
'__invalid_size_argument_for_IOC' cannot appear in a constant-expression    hook_ioctl.cpp  /ApkMonitor/jni line 533    C/C++ Problem
'__invalid_size_argument_for_IOC' cannot appear in a constant-expression    hook_ioctl.cpp  /ApkMonitor/jni line 543    C/C++ Problem
'__invalid_size_argument_for_IOC' cannot appear in a constant-expression    hook_ioctl.cpp  /ApkMonitor/jni line 544    C/C++ Problem
'__invalid_size_argument_for_IOC' cannot appear in a constant-expression    hook_ioctl.cpp  /ApkMonitor/jni line 545    C/C++ Problem
'__invalid_size_argument_for_IOC' cannot appear in a constant-expression    hook_ioctl.cpp  /ApkMonitor/jni line 546    C/C++ Problem
make: **\* [obj/local/armeabi/objs/apihook/hook_ioctl.o] Error 1 ApkMonitor          C/C++ Problem
'__invalid_size_argument_for_IOC' cannot appear in a constant-expression    hook_ioctl.cpp  /ApkMonitor/jni line 547    C/C++ Problem
'__invalid_size_argument_for_IOC' cannot appear in a constant-expression    hook_ioctl.cpp  /ApkMonitor/jni line 548    C/C++ Problem

**Comment by xurubin** [comment]
You'll need to patch ioctl.h in your NDK header files to make it compile, s/_IOC_TYPECHECK(size)/size/g

**Comment by Saisi** [comment]
Maybe I'm missing something, but shouldn't it be  `s/_IOC_TYPECHECK(size)/sizeof(size)/g` ?
And because NDK header files are autogenerated frequently, the changes won't persist. You're probably better off making your own header file

**Comment by Sampson-2016** [comment]
I am a student always using java and  not good at c/c++ ,How to patch ioctl.h?can you help me?Thank you very much .
